//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account_information()
        {
            this.Account_Address_Information = new HashSet<Account_Address_Information>();
            this.Account_Contact_Information = new HashSet<Account_Contact_Information>();
        }
    
        public int account_information_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> account_owner_id { get; set; }
        public Nullable<int> rating_type_id { get; set; }
        public string account_name { get; set; }
        public string account_site { get; set; }
        public Nullable<int> account_type_id { get; set; }
        public string website { get; set; }
        public byte[] account_image { get; set; }
        public Nullable<decimal> no_of_emp { get; set; }
        public Nullable<int> industry_id { get; set; }
        public string ownership_name { get; set; }
        public Nullable<decimal> annual_revenue { get; set; }
        public string account_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Address_Information> Account_Address_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Contact_Information> Account_Contact_Information { get; set; }
        public virtual Company_Information Company_Information { get; set; }
        public virtual Type_Account Type_Account { get; set; }
        public virtual Type_of_Industry Type_of_Industry { get; set; }
        public virtual Type_Rating Type_Rating { get; set; }
        public virtual User_Information User_Information { get; set; }
    }
}
