//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Address_Information
    {
        public int account_address_id { get; set; }
        public Nullable<int> account_information_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string billing_street { get; set; }
        public string shipping_street { get; set; }
        public Nullable<int> billing_city { get; set; }
        public Nullable<int> shipping_city { get; set; }
        public Nullable<int> billing_state { get; set; }
        public Nullable<int> shipping_state { get; set; }
        public string billing_code { get; set; }
        public string shipping_code { get; set; }
        public Nullable<int> billing_country { get; set; }
        public Nullable<int> shipping_country { get; set; }
    
        public virtual Account_information Account_information { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Company_Information Company_Information { get; set; }
        public virtual Country_name Country_name { get; set; }
        public virtual Country_name Country_name1 { get; set; }
        public virtual State_name State_name { get; set; }
        public virtual State_name State_name1 { get; set; }
    }
}
