//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add_Notes
    {
        public int notes_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string Notes { get; set; }
        public string files { get; set; }
        public string owner_name { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
    }
}
