//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class call_duration
    {
        public int call_duration_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> call_id { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public string call_duration1 { get; set; }
        public Nullable<int> call_result { get; set; }
    
        public virtual call_information call_information { get; set; }
        public virtual Call_result Call_result1 { get; set; }
        public virtual Company_Information Company_Information { get; set; }
    }
}
