//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign_Budget_Information
    {
        public int campaign_budget_info_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> campaign_info_id { get; set; }
        public Nullable<decimal> expected_budget { get; set; }
        public Nullable<decimal> budget_cost { get; set; }
        public Nullable<decimal> actual_cost { get; set; }
        public Nullable<decimal> expected_response { get; set; }
    
        public virtual campaign_information campaign_information { get; set; }
        public virtual Company_Information Company_Information { get; set; }
    }
}
