//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign_information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public campaign_information()
        {
            this.Campaign_Budget_Information = new HashSet<Campaign_Budget_Information>();
        }
    
        public int campaign_info_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> compaign_owner_id { get; set; }
        public Nullable<int> campaign_id { get; set; }
        public Nullable<int> campaign_status_id { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign_Budget_Information> Campaign_Budget_Information { get; set; }
        public virtual Company_Information Company_Information { get; set; }
        public virtual Type_of_campaign Type_of_campaign { get; set; }
        public virtual Type_of_campaignstatus Type_of_campaignstatus { get; set; }
        public virtual User_Information User_Information { get; set; }
    }
}
