//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_u_no_emp
    {
        public int company_no_emp_id { get; set; }
        public Nullable<int> company_User_ID { get; set; }
        public string no_emp { get; set; }
        public Nullable<int> Company_id { get; set; }
    
        public virtual Campany_User_Info Campany_User_Info { get; set; }
        public virtual Company_Information Company_Information { get; set; }
    }
}
