//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact_information()
        {
            this.Contact_address_Information = new HashSet<Contact_address_Information>();
            this.contact_contact_information = new HashSet<contact_contact_information>();
        }
    
        public int contact_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> contact_owner_id { get; set; }
        public Nullable<int> leadsource_id { get; set; }
        public Nullable<int> title_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string account_name { get; set; }
        public string department_name { get; set; }
        public byte[] user_image { get; set; }
        public string assistant_name { get; set; }
        public string description { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_address_Information> Contact_address_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_contact_information> contact_contact_information { get; set; }
        public virtual Title Title { get; set; }
        public virtual Type_of_LeadSource Type_of_LeadSource { get; set; }
        public virtual User_Information User_Information { get; set; }
    }
}
