//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_address_Information
    {
        public int contact_address_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public string mailing_street { get; set; }
        public string other_street { get; set; }
        public Nullable<int> mailing_city { get; set; }
        public Nullable<int> other_city { get; set; }
        public Nullable<int> mailing_state { get; set; }
        public Nullable<int> other_state { get; set; }
        public string mailing_zip { get; set; }
        public string other_zip { get; set; }
        public Nullable<int> mailing_country { get; set; }
        public Nullable<int> other_country { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Company_Information Company_Information { get; set; }
        public virtual Contact_information Contact_information { get; set; }
        public virtual Country_name Country_name { get; set; }
        public virtual Country_name Country_name1 { get; set; }
        public virtual State_name State_name { get; set; }
        public virtual State_name State_name1 { get; set; }
    }
}
