//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_contact_information
    {
        public int contact_deatail_id { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string phone_number { get; set; }
        public string home_phone_number { get; set; }
        public string other_phone_number { get; set; }
        public string fax { get; set; }
        public string mobile_number { get; set; }
        public string assistant_phone_number { get; set; }
        public string skype_id { get; set; }
        public string twitter { get; set; }
        public string email_id { get; set; }
        public string secondry_email { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        public virtual Contact_information Contact_information { get; set; }
    }
}
