//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_User
    {
        public int Contact_id { get; set; }
        public string email { get; set; }
        public string full_names { get; set; }
        public string last_name { get; set; }
        public Nullable<int> Contact_owner { get; set; }
        public string Job_Title { get; set; }
        public string phone_Number { get; set; }
        public Nullable<int> LifeCycle_Stage { get; set; }
        public Nullable<int> Lead_Status { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Create_date { get; set; }
        public Nullable<int> Created_by { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        public virtual Lead_Status Lead_Status1 { get; set; }
        public virtual Types_of_Life_Cycle Types_of_Life_Cycle { get; set; }
        public virtual User_Information User_Information { get; set; }
        public virtual User_Information User_Information1 { get; set; }
    }
}
