//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Address_Information> Account_Address_Information { get; set; }
        public virtual DbSet<Account_Contact_Information> Account_Contact_Information { get; set; }
        public virtual DbSet<Account_information> Account_information { get; set; }
        public virtual DbSet<Account_type_Information> Account_type_Information { get; set; }
        public virtual DbSet<Add_Notes> Add_Notes { get; set; }
        public virtual DbSet<Attachment_file> Attachment_file { get; set; }
        public virtual DbSet<call_duration> call_duration { get; set; }
        public virtual DbSet<call_information> call_information { get; set; }
        public virtual DbSet<Call_result> Call_result { get; set; }
        public virtual DbSet<Campaign_Budget_Information> Campaign_Budget_Information { get; set; }
        public virtual DbSet<campaign_information> campaign_information { get; set; }
        public virtual DbSet<Campany_User_Info> Campany_User_Info { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company_contact_info> Company_contact_info { get; set; }
        public virtual DbSet<Company_Information> Company_Information { get; set; }
        public virtual DbSet<Company_u_no_emp> Company_u_no_emp { get; set; }
        public virtual DbSet<Contact_address_Information> Contact_address_Information { get; set; }
        public virtual DbSet<contact_contact_information> contact_contact_information { get; set; }
        public virtual DbSet<Contact_information> Contact_information { get; set; }
        public virtual DbSet<contact_type_for_task> contact_type_for_task { get; set; }
        public virtual DbSet<Contact_User> Contact_User { get; set; }
        public virtual DbSet<Country_name> Country_name { get; set; }
        public virtual DbSet<Deal_information> Deal_information { get; set; }
        public virtual DbSet<document_Information> document_Information { get; set; }
        public virtual DbSet<email_information> email_information { get; set; }
        public virtual DbSet<Event_information> Event_information { get; set; }
        public virtual DbSet<lead_address_information> lead_address_information { get; set; }
        public virtual DbSet<lead_contact_information> lead_contact_information { get; set; }
        public virtual DbSet<lead_information> lead_information { get; set; }
        public virtual DbSet<Lead_Status> Lead_Status { get; set; }
        public virtual DbSet<Num_of_Emp_of_Comp> Num_of_Emp_of_Comp { get; set; }
        public virtual DbSet<Related_to_call> Related_to_call { get; set; }
        public virtual DbSet<Related_to_event> Related_to_event { get; set; }
        public virtual DbSet<Related_to_Task> Related_to_Task { get; set; }
        public virtual DbSet<State_name> State_name { get; set; }
        public virtual DbSet<status_type_for_task> status_type_for_task { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<task_information> task_information { get; set; }
        public virtual DbSet<tbl_Type_TicketSource> tbl_Type_TicketSource { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Type_Account> Type_Account { get; set; }
        public virtual DbSet<type_of_call> type_of_call { get; set; }
        public virtual DbSet<Type_of_campaign> Type_of_campaign { get; set; }
        public virtual DbSet<Type_of_campaignstatus> Type_of_campaignstatus { get; set; }
        public virtual DbSet<Type_of_companies> Type_of_companies { get; set; }
        public virtual DbSet<Type_of_deal> Type_of_deal { get; set; }
        public virtual DbSet<Type_of_Deal_Stage> Type_of_Deal_Stage { get; set; }
        public virtual DbSet<Type_of_Deals_Pipelines> Type_of_Deals_Pipelines { get; set; }
        public virtual DbSet<Type_of_Industry> Type_of_Industry { get; set; }
        public virtual DbSet<Type_of_LeadSource> Type_of_LeadSource { get; set; }
        public virtual DbSet<Type_of_LeadStatus> Type_of_LeadStatus { get; set; }
        public virtual DbSet<Type_of_Ownership> Type_of_Ownership { get; set; }
        public virtual DbSet<Type_of_priority> Type_of_priority { get; set; }
        public virtual DbSet<Type_of_Stage> Type_of_Stage { get; set; }
        public virtual DbSet<Type_Rating> Type_Rating { get; set; }
        public virtual DbSet<Types_of_call> Types_of_call { get; set; }
        public virtual DbSet<Types_of_Life_Cycle> Types_of_Life_Cycle { get; set; }
        public virtual DbSet<Types_of_ticketsStatus> Types_of_ticketsStatus { get; set; }
        public virtual DbSet<Typesoftickets_pipeline> Typesoftickets_pipeline { get; set; }
        public virtual DbSet<User_Contact_Information> User_Contact_Information { get; set; }
        public virtual DbSet<User_Information> User_Information { get; set; }
        public virtual DbSet<User_type> User_type { get; set; }
    }
}
