//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_information
    {
        public int deal_information_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> deal_owner_id { get; set; }
        public string deal_name { get; set; }
        public Nullable<int> deal_type_id { get; set; }
        public string contact_person_name { get; set; }
        public Nullable<decimal> amont { get; set; }
        public string closing_date { get; set; }
        public Nullable<decimal> expected_revenue { get; set; }
        public Nullable<int> deal_pipeline_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Create_date { get; set; }
        public Nullable<int> type_of_dealstage { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        public virtual Type_of_Deal_Stage Type_of_Deal_Stage { get; set; }
        public virtual Type_of_Deals_Pipelines Type_of_Deals_Pipelines { get; set; }
        public virtual User_Information User_Information { get; set; }
        public virtual User_Information User_Information1 { get; set; }
    }
}
