//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_information
    {
        public int email_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string to_id { get; set; }
        public string from_id { get; set; }
        public string subject { get; set; }
        public string message_body { get; set; }
        public string attachment { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
    }
}
