//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lead_address_information
    {
        public int lead_address_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> lead_info_id { get; set; }
        public string zip_code { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company_Information Company_Information { get; set; }
        public virtual Country_name Country_name { get; set; }
        public virtual lead_information lead_information { get; set; }
        public virtual State_name State_name { get; set; }
    }
}
