//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lead_information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lead_information()
        {
            this.lead_address_information = new HashSet<lead_address_information>();
            this.lead_contact_information = new HashSet<lead_contact_information>();
        }
    
        public int lead_info_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> lead_owner_id { get; set; }
        public Nullable<int> title_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string company_name { get; set; }
        public string website_name { get; set; }
        public Nullable<int> leadsource_id { get; set; }
        public Nullable<int> lead_status_id { get; set; }
        public Nullable<int> industry_id { get; set; }
        public Nullable<decimal> no_of_emp { get; set; }
        public byte[] user_image { get; set; }
        public Nullable<decimal> annual_revenue { get; set; }
        public Nullable<int> rating_type_id { get; set; }
        public string description { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lead_address_information> lead_address_information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lead_contact_information> lead_contact_information { get; set; }
        public virtual Title Title { get; set; }
        public virtual Type_of_Industry Type_of_Industry { get; set; }
        public virtual Type_of_LeadSource Type_of_LeadSource { get; set; }
        public virtual Type_of_LeadStatus Type_of_LeadStatus { get; set; }
        public virtual Type_Rating Type_Rating { get; set; }
        public virtual User_Information User_Information { get; set; }
    }
}
