//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lead_contact_information
    {
        public int lead_contact_id { get; set; }
        public Nullable<int> lead_info_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string phone_number { get; set; }
        public string mobile_number { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string secondry_email { get; set; }
        public string skype_id { get; set; }
        public string twitter { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        public virtual lead_information lead_information { get; set; }
    }
}
