//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Num_of_Emp_of_Comp
    {
        public int Num_of_Emp_id { get; set; }
        public string Num_of_Emp { get; set; }
        public Nullable<int> Company_id { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
    }
}
