//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_id { get; set; }
        public string Ticket_name { get; set; }
        public Nullable<int> Ticket_status_id { get; set; }
        public Nullable<int> Ticket_Source_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> priority_type_id { get; set; }
        public string Created_date { get; set; }
        public Nullable<int> Ticket_pipeline_id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Created_by { get; set; }
        public string Date_of_creation { get; set; }
        public Nullable<int> Company_id { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        public virtual tbl_Type_TicketSource tbl_Type_TicketSource { get; set; }
        public virtual Type_of_priority Type_of_priority { get; set; }
        public virtual Types_of_ticketsStatus Types_of_ticketsStatus { get; set; }
        public virtual Typesoftickets_pipeline Typesoftickets_pipeline { get; set; }
        public virtual User_Information User_Information { get; set; }
        public virtual User_Information User_Information1 { get; set; }
    }
}
