//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_of_LeadStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_of_LeadStatus()
        {
            this.lead_information = new HashSet<lead_information>();
        }
    
        public int lead_status_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string lead_status_name { get; set; }
        public string Create_date { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lead_information> lead_information { get; set; }
        public virtual User_Information User_Information { get; set; }
    }
}
