//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_of_deal
    {
        public int deal_type_id { get; set; }
        public string deal_type_name { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Create_date { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        public virtual User_Information User_Information { get; set; }
    }
}
