//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Contact_Information
    {
        public int User_contact_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string mobile_number { get; set; }
        public string land_line_number { get; set; }
        public string fax_number { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual Company_Information Company_Information { get; set; }
        public virtual User_Information User_Information { get; set; }
    }
}
